name: Build Docker Image

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  IMAGE_TAG: avenirhealth-org/sw-projection-storage

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract_branch
        name: Setup Environment
        shell: bash
        run: |
          if [ "${{github.event_name}}" = "pull_request" ];
          then
            LONG_SHA=${{ github.event.pull_request.head.sha }}
            echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            LONG_SHA=${GITHUB_SHA}
            echo "CI_BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          echo "CI_SHA=${LONG_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          file: "./docker/Dockerfile"
          push: false
          load: true
          tags: |
            ghcr.io/${{env.IMAGE_TAG}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Test
        run: ./docker/test-docker.sh ghcr.io/${{env.IMAGE_TAG}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          file: "./docker/Dockerfile"
          push: true
          tags: |
            ghcr.io/${{env.IMAGE_TAG}}:${{steps.extract_branch.outputs.CI_BRANCH}}
